name: Kotlin CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target branch
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Fetch all branches
      run: git fetch origin
    - name: Merge head branch into main
      if: github.event_name == 'pull_request'
      run: git merge origin/${{ github.event.pull_request.head.ref }}
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run ktlint
      run: ./gradlew ktlintCheck
    - name: Run tests
      run: ./gradlew test
